In [61]:
import pandas as pd

In [62]:
dataframe = pd.DataFrame({
    'id': [1, 2, 2, 3, 4, 4, 4],
    'name': ['Alice', 'Bob', 'Bob', 'Charlie', 'David', 'David', 'David'],
    'email': [
        'a@example.com',
        'b@example.com',
        'b@example.com',
        'c@example.com',
        'd@example.com',
        'd@example.com',
        'd@example.com'
    ]
})

In [63]:
dataframe

   id     name          email
0   1    Alice  a@example.com
1   2      Bob  b@example.com
2   2      Bob  b@example.com
3   3  Charlie  c@example.com
4   4    David  d@example.com
5   4    David  d@example.com
6   4    David  d@example.com

In [64]:
clean_data = dataframe.drop_duplicates()

In [65]:
clean_data

   id     name          email
0   1    Alice  a@example.com
1   2      Bob  b@example.com
3   3  Charlie  c@example.com
4   4    David  d@example.com

In [66]:
dataframe = pd.DataFrame({
    'id': [1, 2, 2, 3, 4, 4, 4],
    'name': ['Alice', 'Bob', 'Bob', 'Charlie', 'David', 'David', 'David'],
    'email': [
        'a@example.com',
        'b@example.com',
        'b@example.com',
        'c@example.com',
        'd@example.com',
        'd@example.com',
        'd@example.com'
    ],
    'email1': [
        'a@example.com',
        'b@example.com',
        'b@example.com',
        'c@example.com',
        'd@example.com',
        'd@example.com',
        'd@example.com'
    ],
})

In [67]:
dataframe

   id     name          email         email1
0   1    Alice  a@example.com  a@example.com
1   2      Bob  b@example.com  b@example.com
2   2      Bob  b@example.com  b@example.com
3   3  Charlie  c@example.com  c@example.com
4   4    David  d@example.com  d@example.com
5   4    David  d@example.com  d@example.com
6   4    David  d@example.com  d@example.com

In [68]:
duplicate_columns = []

In [69]:
for i in dataframe.columns:
    for j in dataframe.columns:
        if i!=j and dataframe[i].equals(dataframe[j]):
            duplicate_columns.append((i,j))

In [70]:
duplicate_columns

[('email', 'email1'), ('email1', 'email')]

In [71]:
dataframe.drop(columns=['email1'])

   id     name          email
0   1    Alice  a@example.com
1   2      Bob  b@example.com
2   2      Bob  b@example.com
3   3  Charlie  c@example.com
4   4    David  d@example.com
5   4    David  d@example.com
6   4    David  d@example.com

In [72]:
import pandas as pd
import numpy as np

# Create a sample DataFrame with an outlier
data = {
    'id': [1, 2, 3, 4, 5, 6],
    'age': [25, 27, 29, 31, 120, 28],   # 120 is an outlier
    'salary': [3000, 3200, 3500, 4000, 5000, 100000]  # 100000 is an outlier
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
   id  age  salary
0   1   25    3000
1   2   27    3200
2   3   29    3500
3   4   31    4000
4   5  120    5000
5   6   28  100000

In [73]:
outlier_info = {}
for i in ['age', 'salary']:
    q1 = df[i].quantile(0.25)
    q3 = df[i].quantile(0.75)

    IQR = q3-q1
    lower_bound = q1- 1.5*IQR
    upper_bound = q3 + 1.5*IQR

    x = df[i]< lower_bound | df[i]>upper_bound
    outlier_info[i] = df[x]

TypeError: Cannot perform 'ror_' with a dtyped [int64] array and scalar of type [bool]

In [ ]:
outlier_info

In [ ]:
import pandas as pd

data = {
    'department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT', 'Sales'],
    'employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'salary': [5000, 6000, 4500, 4700, 7000, 7200, 5200],
    'bonus': [500, 600, 300, 400, 700, 800, 550]
}

In [ ]:
dataframe = pd.DataFrame(data)

In [ ]:
dataframe

In [ ]:
group = dataframe.groupby('department')

In [ ]:
group.agg(
    {'salary':'sum',
     'bonus':'sum'
    }
)

In [74]:
dataframe = pd.DataFrame({
    'Age':[10,20,30],
    "Gender":["M","F","M"],
    "Graduation":["UG","PG","P.hd"],
    "Target":["Yes","Yes","No"]}
)

In [75]:
dataframe

   Age Gender Graduation Target
0   10      M         UG    Yes
1   20      F         PG    Yes
2   30      M       P.hd     No

In [76]:
from sklearn.preprocessing import OrdinalEncoder

In [79]:
oe = OrdinalEncoder(categories=[["P.hd","PG","UG"]])

In [80]:
oe.fit_transform(dataframe[["Graduation"]])

array([[2.],
       [1.],
       [0.]])

In [81]:
dataframe

   Age Gender Graduation Target
0   10      M         UG    Yes
1   20      F         PG    Yes
2   30      M       P.hd     No

In [82]:
dataframe["Graduation"]= oe.fit_transform(dataframe[["Graduation"]])

In [83]:
dataframe

   Age Gender  Graduation Target
0   10      M         2.0    Yes
1   20      F         1.0    Yes
2   30      M         0.0     No

In [86]:
df2 = pd.get_dummies(dataframe["Gender"])

In [88]:
x = dataframe.drop(columns="Gender")

In [91]:
pd.concat([x,df2],axis=1)

   Age  Graduation Target      F      M
0   10         2.0    Yes  False   True
1   20         1.0    Yes   True  False
2   30         0.0     No  False   True

In [92]:
from sklearn.preprocessing import LabelEncoder

In [93]:
le = LabelEncoder()

In [94]:
le.fit_transform(dataframe["Target"])

array([1, 1, 0])

In [95]:
dataframe["Target"]= le.fit_transform(dataframe["Target"])

In [96]:
dataframe

   Age Gender  Graduation  Target
0   10      M         2.0       1
1   20      F         1.0       1
2   30      M         0.0       0